name: Latest Episodes

on:
  schedule:
    # Runs every hour
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-podcast:
    name: Update this repo's README with latest Podcast
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://erreur200.com/rss.xml"
