name: Podcast update

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs every week at midnight on Sunday
    - cron: '0 0 * * 0'

permissions:
  contents: write

jobs:
  update-readme:
    name: Update this repo's README with latest podcast episodes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Erreur 200
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          comment_tag_name: PODCAST-LIST
          feed_list: "https://erreur200.com/rss.xml"
